### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Morette** [training-center/python-study-group#1]
Pessoal, encontrei esse roadmap de back. Ele é bem parecido com o de front. O que acham da parte de Python?

https://camo.githubusercontent.com/a69353cebac96bd2e82b45771d6edd32715ca0c3/68747470733a2f2f692e696d6775722e636f6d2f6d3956385a69562e706e67

**Comment by mstuttgart** [comment]
@Morette boa! Eu já conhecia esse *roadmap*. Acho uma ótima referência e seria interessante utilizar ele como guia, pelo menos no inicio.

https://github.com/kamranahmedse/developer-roadmap

![](https://camo.githubusercontent.com/a69353cebac96bd2e82b45771d6edd32715ca0c3/68747470733a2f2f692e696d6775722e636f6d2f6d3956385a69562e706e67)

**Comment by an-jorge** [comment]
Interessante

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by mstuttgart** [comment]
@Diego-Brocanelli por mim tudo bem.

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno.
